export interface IRealPriceItem {
  // 成交案件類型
  CASE_T: string;
  // 行政區
  DISTRICT: string;
  // 交易標的/租賃標的
  CASE_F: string;
  // 土地區段位置或建物區門牌
  LOCATION: string;
  // 土地移轉總面積(坪)/土地租賃總面積(坪)
  LANDA: string;
  // 都市土地使用分區
  LANDA_Z: string;
  // 交易年月
  SDATE: string;
  // 交易筆棟數/租賃筆棟數
  SCNT: string;
  // 移轉層次
  SBUILD: string;
  // 總樓層數
  TBUILD: string;
  // 建物型態
  BUITYPE: string;
  // 主要用途
  PBUILD: string;
  // 主要建材
  MBUILD: string;
  // 建築完成年月
  FDATE: string;
  // 建物移轉總面積(坪)/租賃總面積(坪)
  FAREA: string;
  // 建物現況格局_房
  BUILD_R: string;
  // 建物現況格局_廳
  BUILD_L: string;
  // 建物現況格局_衛
  BUILD_B: string;
  // 建物現況格局_隔間
  BUILD_P: string;
  // 有無管理組織
  RULE: string;
  // 有無附傢俱
  BUILD_C: string;
  // 交易總價(萬元)/租賃總價(萬元)
  TPRICE: string;
  // 交易單價(萬元/坪)/租賃單價(元/坪)
  UPRICE: string;
  // 單價是否含車位
  UPNOTE: string;
  // 車位類別及數量
  PARKTYPE: string;
  // 車位移轉總面積(坪)/車位租賃總面積(坪)
  PAREA: string;
  // 車位移轉總價(萬元)/車位租賃總價(元)
  PPRICE: string;
  // 備註
  RMNOTE: string;
}
